### PR TITLE
Week 3 thoughts added + Renata's assignment

### PR DESCRIPTION
**Pull request by musarena**
Please ignore the file commented "Macro assignment - Renata" -> the correct one is "Renata's assignment added" which is supposed to be in the Macro folder.
Thanks,
Renata

### CODE REVIEW

**Comment by lwjohnst86** [comment]
Thanks a lot Renata! You could actually just delete the `renata-musa-NHL.sas` (not `macros/renata-musa-NHL.sas`!)file from your file manager (explorer?), then do:

```
cd sandbox ## where ever it is located
git rm renata-musa-NHL.sas
git commit -m "Removed extra file"
git push
```

That way we don't have an extra file hanging around :smile:

**Comment by musarena** [comment]
The extra file has been successfully removed. Excellent stuff! Thanks a lot Luke!

**Comment by lwjohnst86** [comment]
Hey @musarena I think that for some reason when you deleted the file, it also closed the the pull request. Could you do another pull request again? So I can merge your files?

**Comment by musarena** [comment]
I probably closed the pull request by error thinking I am closing the
window with updates/comments. :-) Everything should be fine now. Thanks
Luke!

Renata

**Pull request closed without merging**
